// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes = "bytes", tag = "1")]
    pub encoded_txn: ::prost::bytes::Bytes,
    #[prost(bytes = "vec", tag = "2")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InclusionList {
    #[prost(message, repeated, tag = "1")]
    pub encoded_txns: ::prost::alloc::vec::Vec<Transaction>,
    #[prost(uint64, tag = "2")]
    pub round: u64,
    #[prost(uint64, tag = "3")]
    pub consensus_timestamp: u64,
    #[prost(uint64, tag = "4")]
    pub delayed_messages_read: u64,
}
