// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InclusionList {
    #[prost(bytes = "bytes", repeated, tag = "1")]
    pub encoded_txns: ::prost::alloc::vec::Vec<::prost::bytes::Bytes>,
    #[prost(uint64, tag = "2")]
    pub round: u64,
    #[prost(uint64, tag = "3")]
    pub consensus_timestamp: u64,
    #[prost(uint64, tag = "4")]
    pub delayed_messages_read: u64,
}
