// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: forward.proto

package go_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatchupRound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         uint64                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchupRound) Reset() {
	*x = CatchupRound{}
	mi := &file_forward_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupRound) ProtoMessage() {}

func (x *CatchupRound) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchupRound.ProtoReflect.Descriptor instead.
func (*CatchupRound) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{0}
}

func (x *CatchupRound) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type TimeboostState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*TimeboostState_Catchup
	//	*TimeboostState_AwaitingHandover
	State         isTimeboostState_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeboostState) Reset() {
	*x = TimeboostState{}
	mi := &file_forward_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeboostState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeboostState) ProtoMessage() {}

func (x *TimeboostState) ProtoReflect() protoreflect.Message {
	mi := &file_forward_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeboostState.ProtoReflect.Descriptor instead.
func (*TimeboostState) Descriptor() ([]byte, []int) {
	return file_forward_proto_rawDescGZIP(), []int{1}
}

func (x *TimeboostState) GetState() isTimeboostState_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *TimeboostState) GetCatchup() *CatchupRound {
	if x != nil {
		if x, ok := x.State.(*TimeboostState_Catchup); ok {
			return x.Catchup
		}
	}
	return nil
}

func (x *TimeboostState) GetAwaitingHandover() bool {
	if x != nil {
		if x, ok := x.State.(*TimeboostState_AwaitingHandover); ok {
			return x.AwaitingHandover
		}
	}
	return false
}

type isTimeboostState_State interface {
	isTimeboostState_State()
}

type TimeboostState_Catchup struct {
	Catchup *CatchupRound `protobuf:"bytes,1,opt,name=catchup,proto3,oneof"`
}

type TimeboostState_AwaitingHandover struct {
	AwaitingHandover bool `protobuf:"varint,2,opt,name=awaiting_handover,json=awaitingHandover,proto3,oneof"`
}

func (*TimeboostState_Catchup) isTimeboostState_State() {}

func (*TimeboostState_AwaitingHandover) isTimeboostState_State() {}

var File_forward_proto protoreflect.FileDescriptor

const file_forward_proto_rawDesc = "" +
	"\n" +
	"\rforward.proto\x12\aforward\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14inclusion_list.proto\"$\n" +
	"\fCatchupRound\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x04R\x05round\"{\n" +
	"\x0eTimeboostState\x121\n" +
	"\acatchup\x18\x01 \x01(\v2\x15.forward.CatchupRoundH\x00R\acatchup\x12-\n" +
	"\x11awaiting_handover\x18\x02 \x01(\bH\x00R\x10awaitingHandoverB\a\n" +
	"\x05state2\xa2\x01\n" +
	"\n" +
	"ForwardApi\x12I\n" +
	"\x13SubmitInclusionList\x12\x18.inclusion.InclusionList\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x14UpdateTimeboostState\x12\x17.forward.TimeboostState\x1a\x16.google.protobuf.Empty\"\x00B9Z7github.com/EspressoSystems/timeboost-proto/go-generatedb\x06proto3"

var (
	file_forward_proto_rawDescOnce sync.Once
	file_forward_proto_rawDescData []byte
)

func file_forward_proto_rawDescGZIP() []byte {
	file_forward_proto_rawDescOnce.Do(func() {
		file_forward_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forward_proto_rawDesc), len(file_forward_proto_rawDesc)))
	})
	return file_forward_proto_rawDescData
}

var file_forward_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_forward_proto_goTypes = []any{
	(*CatchupRound)(nil),   // 0: forward.CatchupRound
	(*TimeboostState)(nil), // 1: forward.TimeboostState
	(*InclusionList)(nil),  // 2: inclusion.InclusionList
	(*emptypb.Empty)(nil),  // 3: google.protobuf.Empty
}
var file_forward_proto_depIdxs = []int32{
	0, // 0: forward.TimeboostState.catchup:type_name -> forward.CatchupRound
	2, // 1: forward.ForwardApi.SubmitInclusionList:input_type -> inclusion.InclusionList
	1, // 2: forward.ForwardApi.UpdateTimeboostState:input_type -> forward.TimeboostState
	3, // 3: forward.ForwardApi.SubmitInclusionList:output_type -> google.protobuf.Empty
	3, // 4: forward.ForwardApi.UpdateTimeboostState:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_forward_proto_init() }
func file_forward_proto_init() {
	if File_forward_proto != nil {
		return
	}
	file_inclusion_list_proto_init()
	file_forward_proto_msgTypes[1].OneofWrappers = []any{
		(*TimeboostState_Catchup)(nil),
		(*TimeboostState_AwaitingHandover)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forward_proto_rawDesc), len(file_forward_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forward_proto_goTypes,
		DependencyIndexes: file_forward_proto_depIdxs,
		MessageInfos:      file_forward_proto_msgTypes,
	}.Build()
	File_forward_proto = out.File
	file_forward_proto_goTypes = nil
	file_forward_proto_depIdxs = nil
}
