// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: forward.proto

package go_generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForwardApi_SubmitInclusionList_FullMethodName  = "/forward.ForwardApi/SubmitInclusionList"
	ForwardApi_UpdateTimeboostState_FullMethodName = "/forward.ForwardApi/UpdateTimeboostState"
)

// ForwardApiClient is the client API for ForwardApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForwardApiClient interface {
	SubmitInclusionList(ctx context.Context, in *InclusionList, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateTimeboostState(ctx context.Context, in *TimeboostState, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type forwardApiClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardApiClient(cc grpc.ClientConnInterface) ForwardApiClient {
	return &forwardApiClient{cc}
}

func (c *forwardApiClient) SubmitInclusionList(ctx context.Context, in *InclusionList, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ForwardApi_SubmitInclusionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwardApiClient) UpdateTimeboostState(ctx context.Context, in *TimeboostState, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ForwardApi_UpdateTimeboostState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardApiServer is the server API for ForwardApi service.
// All implementations must embed UnimplementedForwardApiServer
// for forward compatibility.
type ForwardApiServer interface {
	SubmitInclusionList(context.Context, *InclusionList) (*emptypb.Empty, error)
	UpdateTimeboostState(context.Context, *TimeboostState) (*emptypb.Empty, error)
	mustEmbedUnimplementedForwardApiServer()
}

// UnimplementedForwardApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwardApiServer struct{}

func (UnimplementedForwardApiServer) SubmitInclusionList(context.Context, *InclusionList) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitInclusionList not implemented")
}
func (UnimplementedForwardApiServer) UpdateTimeboostState(context.Context, *TimeboostState) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTimeboostState not implemented")
}
func (UnimplementedForwardApiServer) mustEmbedUnimplementedForwardApiServer() {}
func (UnimplementedForwardApiServer) testEmbeddedByValue()                    {}

// UnsafeForwardApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardApiServer will
// result in compilation errors.
type UnsafeForwardApiServer interface {
	mustEmbedUnimplementedForwardApiServer()
}

func RegisterForwardApiServer(s grpc.ServiceRegistrar, srv ForwardApiServer) {
	// If the following call pancis, it indicates UnimplementedForwardApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwardApi_ServiceDesc, srv)
}

func _ForwardApi_SubmitInclusionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InclusionList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardApiServer).SubmitInclusionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardApi_SubmitInclusionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardApiServer).SubmitInclusionList(ctx, req.(*InclusionList))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwardApi_UpdateTimeboostState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeboostState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardApiServer).UpdateTimeboostState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwardApi_UpdateTimeboostState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardApiServer).UpdateTimeboostState(ctx, req.(*TimeboostState))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwardApi_ServiceDesc is the grpc.ServiceDesc for ForwardApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forward.ForwardApi",
	HandlerType: (*ForwardApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitInclusionList",
			Handler:    _ForwardApi_SubmitInclusionList_Handler,
		},
		{
			MethodName: "UpdateTimeboostState",
			Handler:    _ForwardApi_UpdateTimeboostState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forward.proto",
}
