// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: inclusion_list.proto

package go_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InclusionList struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EncodedTxns         [][]byte               `protobuf:"bytes,1,rep,name=encoded_txns,json=encodedTxns,proto3" json:"encoded_txns,omitempty"`
	Round               uint64                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	ConsensusTimestamp  uint64                 `protobuf:"varint,3,opt,name=consensus_timestamp,json=consensusTimestamp,proto3" json:"consensus_timestamp,omitempty"`
	DelayedMessagesRead uint64                 `protobuf:"varint,4,opt,name=delayed_messages_read,json=delayedMessagesRead,proto3" json:"delayed_messages_read,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InclusionList) Reset() {
	*x = InclusionList{}
	mi := &file_inclusion_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionList) ProtoMessage() {}

func (x *InclusionList) ProtoReflect() protoreflect.Message {
	mi := &file_inclusion_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionList.ProtoReflect.Descriptor instead.
func (*InclusionList) Descriptor() ([]byte, []int) {
	return file_inclusion_list_proto_rawDescGZIP(), []int{0}
}

func (x *InclusionList) GetEncodedTxns() [][]byte {
	if x != nil {
		return x.EncodedTxns
	}
	return nil
}

func (x *InclusionList) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *InclusionList) GetConsensusTimestamp() uint64 {
	if x != nil {
		return x.ConsensusTimestamp
	}
	return 0
}

func (x *InclusionList) GetDelayedMessagesRead() uint64 {
	if x != nil {
		return x.DelayedMessagesRead
	}
	return 0
}

var File_inclusion_list_proto protoreflect.FileDescriptor

const file_inclusion_list_proto_rawDesc = "" +
	"\n" +
	"\x14inclusion_list.proto\x12\tinclusion\"\xad\x01\n" +
	"\rInclusionList\x12!\n" +
	"\fencoded_txns\x18\x01 \x03(\fR\vencodedTxns\x12\x14\n" +
	"\x05round\x18\x02 \x01(\x04R\x05round\x12/\n" +
	"\x13consensus_timestamp\x18\x03 \x01(\x04R\x12consensusTimestamp\x122\n" +
	"\x15delayed_messages_read\x18\x04 \x01(\x04R\x13delayedMessagesReadB9Z7github.com/EspressoSystems/timeboost-proto/go-generatedb\x06proto3"

var (
	file_inclusion_list_proto_rawDescOnce sync.Once
	file_inclusion_list_proto_rawDescData []byte
)

func file_inclusion_list_proto_rawDescGZIP() []byte {
	file_inclusion_list_proto_rawDescOnce.Do(func() {
		file_inclusion_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inclusion_list_proto_rawDesc), len(file_inclusion_list_proto_rawDesc)))
	})
	return file_inclusion_list_proto_rawDescData
}

var file_inclusion_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_inclusion_list_proto_goTypes = []any{
	(*InclusionList)(nil), // 0: inclusion.InclusionList
}
var file_inclusion_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inclusion_list_proto_init() }
func file_inclusion_list_proto_init() {
	if File_inclusion_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inclusion_list_proto_rawDesc), len(file_inclusion_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inclusion_list_proto_goTypes,
		DependencyIndexes: file_inclusion_list_proto_depIdxs,
		MessageInfos:      file_inclusion_list_proto_msgTypes,
	}.Build()
	File_inclusion_list_proto = out.File
	file_inclusion_list_proto_goTypes = nil
	file_inclusion_list_proto_depIdxs = nil
}
