// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: internal.proto

package go_generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalApi_SubmitBlock_FullMethodName = "/internal.InternalApi/SubmitBlock"
)

// InternalApiClient is the client API for InternalApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalApiClient interface {
	SubmitBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type internalApiClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalApiClient(cc grpc.ClientConnInterface) InternalApiClient {
	return &internalApiClient{cc}
}

func (c *internalApiClient) SubmitBlock(ctx context.Context, in *Block, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, InternalApi_SubmitBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalApiServer is the server API for InternalApi service.
// All implementations must embed UnimplementedInternalApiServer
// for forward compatibility.
type InternalApiServer interface {
	SubmitBlock(context.Context, *Block) (*emptypb.Empty, error)
	mustEmbedUnimplementedInternalApiServer()
}

// UnimplementedInternalApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalApiServer struct{}

func (UnimplementedInternalApiServer) SubmitBlock(context.Context, *Block) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitBlock not implemented")
}
func (UnimplementedInternalApiServer) mustEmbedUnimplementedInternalApiServer() {}
func (UnimplementedInternalApiServer) testEmbeddedByValue()                     {}

// UnsafeInternalApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalApiServer will
// result in compilation errors.
type UnsafeInternalApiServer interface {
	mustEmbedUnimplementedInternalApiServer()
}

func RegisterInternalApiServer(s grpc.ServiceRegistrar, srv InternalApiServer) {
	// If the following call pancis, it indicates UnimplementedInternalApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalApi_ServiceDesc, srv)
}

func _InternalApi_SubmitBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Block)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalApiServer).SubmitBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalApi_SubmitBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalApiServer).SubmitBlock(ctx, req.(*Block))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalApi_ServiceDesc is the grpc.ServiceDesc for InternalApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.InternalApi",
	HandlerType: (*InternalApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitBlock",
			Handler:    _InternalApi_SubmitBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}
