name: Validate Go Module

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  generate-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Validate Go module
      run: |
        cd go-generated
        go mod tidy
        go build ./...