name: Release Go Package

on:
  push:
    tags:
      - 'v*'

env:
  MODULE_PATH: github.com/EspressoSystems/timeboost-proto

jobs:
  generate-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    
    - name: Generate Go code
      run: |
        make generate
        mkdir -p pkg
        find generated -type f -name '*.go' -exec mv {} pkg/ \;
        rm -rf generated
        cd pkg
        go mod init $MODULE_PATH
        go get google.golang.org/protobuf@v1.28
        go get google.golang.org/grpc@v1.2
        go mod tidy
      
    - name: Package module
      run: |
        cd pkg
        tar -czvf ../timeboost-proto-go.tar.gz --exclude='go.sum' .
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: timeboost-proto-go.tar.gz