name: Release Go Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  generate-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    
    - name: Generate Go code
      run: make generate
      
    - name: Package module
      run: |
        cd tmp/go
        tar -czvf ../timeboost-proto-go.tar.gz .
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: tmp/timeboost-proto-go.tar.gz